[package]
name = "error-code-derive"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
darling = "^0.20.8"
proc-macro2 = "^1.0.79"
quote = "^1.0.35"
syn = { version = "^2.0.57", features = ["extra-traits"] }
